spring:
  main:
    banner-mode: "off"
  h2:
    console:
      enabled: true
      path: '/console'
  datasource:
    url: 'jdbc:h2:file:./target/db'
  jpa:
    hibernate:
      ddl-auto: 'create-drop'

task.allowMultipleTasksFromTemplate: true
